# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_CADDigitizeSettings.ui'
#
# Created: Mon Oct 27 06:46:04 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CADDigitizeSettings(object):
    def setupUi(self, CADDigitizeSettings):
        CADDigitizeSettings.setObjectName(_fromUtf8("CADDigitizeSettings"))
        CADDigitizeSettings.resize(558, 429)
        self.layoutWidget = QtGui.QWidget(CADDigitizeSettings)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 541, 411))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.CircleTab = QtGui.QWidget()
        self.CircleTab.setObjectName(_fromUtf8("CircleTab"))
        self.layoutWidget1 = QtGui.QWidget(self.CircleTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 134, 39))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.circleSegmentsSpinbox = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.circleSegmentsSpinbox.setDecimals(0)
        self.circleSegmentsSpinbox.setMinimum(4.0)
        self.circleSegmentsSpinbox.setMaximum(3600.0)
        self.circleSegmentsSpinbox.setProperty("value", 8.0)
        self.circleSegmentsSpinbox.setObjectName(_fromUtf8("circleSegmentsSpinbox"))
        self.verticalLayout_5.addWidget(self.circleSegmentsSpinbox)
        self.tabWidget.addTab(self.CircleTab, _fromUtf8(""))
        self.EllipseTab = QtGui.QWidget()
        self.EllipseTab.setObjectName(_fromUtf8("EllipseTab"))
        self.layoutWidget2 = QtGui.QWidget(self.EllipseTab)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 134, 39))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.ellipsePointsSpinbox = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.ellipsePointsSpinbox.setDecimals(0)
        self.ellipsePointsSpinbox.setMinimum(4.0)
        self.ellipsePointsSpinbox.setMaximum(3600.0)
        self.ellipsePointsSpinbox.setProperty("value", 8.0)
        self.ellipsePointsSpinbox.setObjectName(_fromUtf8("ellipsePointsSpinbox"))
        self.verticalLayout_4.addWidget(self.ellipsePointsSpinbox)
        self.tabWidget.addTab(self.EllipseTab, _fromUtf8(""))
        self.ArcTab = QtGui.QWidget()
        self.ArcTab.setObjectName(_fromUtf8("ArcTab"))
        self.layoutWidget3 = QtGui.QWidget(self.ArcTab)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 511, 301))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget3)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioFeaturePitch = QtGui.QRadioButton(self.groupBox)
        self.radioFeaturePitch.setChecked(True)
        self.radioFeaturePitch.setObjectName(_fromUtf8("radioFeaturePitch"))
        self.horizontalLayout.addWidget(self.radioFeaturePitch)
        self.ArcFeaturePitch = QtGui.QDoubleSpinBox(self.groupBox)
        self.ArcFeaturePitch.setEnabled(True)
        self.ArcFeaturePitch.setDecimals(1)
        self.ArcFeaturePitch.setMaximum(100.0)
        self.ArcFeaturePitch.setProperty("value", 2.0)
        self.ArcFeaturePitch.setObjectName(_fromUtf8("ArcFeaturePitch"))
        self.horizontalLayout.addWidget(self.ArcFeaturePitch)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioFeatureAngle = QtGui.QRadioButton(self.groupBox)
        self.radioFeatureAngle.setObjectName(_fromUtf8("radioFeatureAngle"))
        self.horizontalLayout_2.addWidget(self.radioFeatureAngle)
        self.ArcFeatureAngle = QtGui.QDoubleSpinBox(self.groupBox)
        self.ArcFeatureAngle.setDecimals(1)
        self.ArcFeatureAngle.setProperty("value", 1.0)
        self.ArcFeatureAngle.setObjectName(_fromUtf8("ArcFeatureAngle"))
        self.horizontalLayout_2.addWidget(self.ArcFeatureAngle)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget4 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 113, 40))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.ArcClockWise = QtGui.QRadioButton(self.layoutWidget4)
        self.ArcClockWise.setChecked(True)
        self.ArcClockWise.setObjectName(_fromUtf8("ArcClockWise"))
        self.verticalLayout_2.addWidget(self.ArcClockWise)
        self.ArcCounterClockWise = QtGui.QRadioButton(self.layoutWidget4)
        self.ArcCounterClockWise.setObjectName(_fromUtf8("ArcCounterClockWise"))
        self.verticalLayout_2.addWidget(self.ArcCounterClockWise)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.ArcTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CADDigitizeSettings)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CADDigitizeSettings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CADDigitizeSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(CADDigitizeSettings)

    def retranslateUi(self, CADDigitizeSettings):
        CADDigitizeSettings.setWindowTitle(_translate("CADDigitizeSettings", "CADDigitize Settings", None))
        self.label_2.setText(_translate("CADDigitizeSettings", "Quadrant segment", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CircleTab), _translate("CADDigitizeSettings", "Circle", None))
        self.label.setText(_translate("CADDigitizeSettings", "Number of points on ellipse", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.EllipseTab), _translate("CADDigitizeSettings", "Ellipse", None))
        self.groupBox.setTitle(_translate("CADDigitizeSettings", "Feature Segmentation", None))
        self.radioFeaturePitch.setText(_translate("CADDigitizeSettings", "Pitch", None))
        self.ArcFeaturePitch.setPrefix(_translate("CADDigitizeSettings", "Millimeter(s) ", None))
        self.radioFeatureAngle.setText(_translate("CADDigitizeSettings", "Angle", None))
        self.ArcFeatureAngle.setPrefix(_translate("CADDigitizeSettings", "Degree(s) ", None))
        self.groupBox_2.setTitle(_translate("CADDigitizeSettings", "Angle Direction", None))
        self.ArcClockWise.setText(_translate("CADDigitizeSettings", "ClockWise", None))
        self.ArcCounterClockWise.setText(_translate("CADDigitizeSettings", "CounterClockWise", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ArcTab), _translate("CADDigitizeSettings", "Arcs", None))

